#!/usr/bin/env bash
# index-requirements.sh — regenerate INDEX.md and INDEX.html from all four states
#
# Usage:
#   index-requirements.sh
#   index-requirements.sh --root <path>
#
# Scans <root>/internal-docs/reqs/{proposed,todo,current}/ for files and
# <root>/internal-docs/reqs/history/ for snapshots. Extracts frontmatter
# and summary lines. Writes:
#   <root>/internal-docs/reqs/INDEX.md   — pure markdown, GitHub-viewable
#   <root>/internal-docs/reqs/INDEX.html — interactive JS-rendered view
#
# The four states:
#   proposed/ — draft plans, not ready to work on
#   todo/     — ready plans (change descriptions)
#   current/  — how the system works now (pure description)
#   history/  — evolution log (completed plans + superseded snapshots)

set -euo pipefail

# Args
ROOT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root) ROOT="$2"; shift 2 ;;
        -h|--help)
            head -12 "$0" | tail -10
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$ROOT" ]]; then
    ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
fi

REQS_DIR="$ROOT/internal-docs/reqs"
PROPOSED_DIR="$REQS_DIR/proposed"
TODO_DIR="$REQS_DIR/todo"
CURRENT_DIR="$REQS_DIR/current"
HISTORY_DIR="$REQS_DIR/history"
INDEX_MD="$REQS_DIR/INDEX.md"
INDEX_HTML="$REQS_DIR/INDEX.html"

# --- Helper: extract frontmatter field ---
# $1 = filepath, $2 = field name (e.g. "status", "created")
extract_fm() {
    awk -v field="$2" '
        /^---$/{c++; next}
        c==1 && $0 ~ "^"field":" {
            gsub(/^[^:]+:[[:space:]]*"?/, "")
            gsub(/"$/, "")
            print
            exit
        }
        c==1 && $0 ~ "^[[:space:]]+"field":" {
            gsub(/^[[:space:]]*[^:]+:[[:space:]]*"?/, "")
            gsub(/"$/, "")
            print
            exit
        }
    ' "$1"
}

# --- Helper: extract summary (first non-empty, non-heading, non-frontmatter line) ---
extract_summary() {
    awk '
        /^---$/{fm++; next}
        fm<2 && /^#/{next}
        fm<2 && /^[[:space:]]*$/{next}
        fm>=2 {print; exit}
    ' "$1" | head -1
}

# --- Helper: truncate to N chars ---
truncate() {
    local str="$1"
    local max="$2"
    if [[ ${#str} -gt $max ]]; then
        echo "${str:0:$((max-3))}..."
    else
        echo "$str"
    fi
}

# --- Collect entries from each state ---
# Format: state|proj|module|slug|status|summary|filepath
declare -a ALL_ENTRIES

collect_state() {
    local state="$1"
    local dir="$2"
    local glob="$3"

    [[ ! -d "$dir" ]] && return 0

    while IFS= read -r filepath; do
        [[ -z "$filepath" ]] && continue
        [[ ! -f "$filepath" ]] && continue

        local rel proj module filename slug status summary
        rel="${filepath#$dir/}"
        proj="${rel%%/*}"
        local rest="${rel#*/}"
        module="${rest%%/*}"
        filename="${rest#*/}"

        # Parse slug from filename
        if [[ "$state" == "history" ]]; then
            # history: req-YYYYMMDDHHmm-{slug}.md or todo-YYYYMMDDHHmm-{slug}.md
            if [[ "$filename" == req-* ]]; then
                slug="${filename#req-*-}"
            elif [[ "$filename" == todo-* ]]; then
                slug="${filename#todo-*-}"
            else
                slug="${filename%.md}"
            fi
        else
            # proposed/todo/current: {proj}_{module}_{slug}.md
            slug="${filename#${proj}_${module}_}"
        fi
        slug="${slug%.md}"

        status="$(extract_fm "$filepath" "status")"
        [[ -z "$status" ]] && status="$state"

        summary="$(extract_summary "$filepath")"
        summary="$(truncate "$summary" 100)"

        ALL_ENTRIES+=("$state|$proj|$module|$slug|$status|$summary|$filepath")
    done < <(find "$dir" -name "$glob" -type f 2>/dev/null | sort)
}

collect_state "proposed" "$PROPOSED_DIR" '*.md'
collect_state "todo"     "$TODO_DIR"     '*.md'
collect_state "current"  "$CURRENT_DIR"  '*.md'
collect_state "history"  "$HISTORY_DIR"  'req-*.md'
collect_state "history"  "$HISTORY_DIR"  'todo-*.md'

# --- Generate INDEX.md (pure markdown, GitHub-viewable) ---
generate_index_md() {
    {
        echo "# Requirements Ledger"
        echo ""
        echo "_Generated by index-requirements.sh. Do not edit manually._"
        echo ""
        echo "Four-state lifecycle: \`proposed/\` → \`todo/\` → \`current/\` + \`history/\`"
        echo ""

        for state in proposed todo current history; do
            # Count entries for this state
            local count=0
            for entry in "${ALL_ENTRIES[@]}"; do
                [[ "$entry" == "$state|"* ]] && count=$((count + 1))
            done

            if [[ $count -eq 0 ]]; then
                continue
            fi

            local state_label
            case "$state" in
                proposed) state_label="Proposed (draft plans, not ready)" ;;
                todo)     state_label="Todo (ready to implement)" ;;
                current)  state_label="Current (how the system works now)" ;;
                history)  state_label="History (evolution log)" ;;
            esac

            echo "---"
            echo ""
            echo "## $state_label"
            echo ""

            local current_proj="" current_module=""

            for entry in "${ALL_ENTRIES[@]}"; do
                local e_state e_proj e_module e_slug e_status e_summary e_filepath
                IFS='|' read -r e_state e_proj e_module e_slug e_status e_summary e_filepath <<< "$entry"
                [[ "$e_state" != "$state" ]] && continue

                if [[ "$e_proj" != "$current_proj" ]]; then
                    current_proj="$e_proj"
                    current_module=""
                    echo "### $e_proj"
                fi

                if [[ "$e_module" != "$current_module" ]]; then
                    current_module="$e_module"
                    echo ""
                    echo "#### $e_module"
                    echo ""
                fi

                # Build link relative to REQS_DIR
                local relpath="${e_filepath#$REQS_DIR/}"
                local link_text="$e_slug"

                if [[ "$e_status" == "superseded" ]]; then
                    echo "- [$link_text]($relpath) — $e_summary _(superseded)_"
                elif [[ "$e_status" == "proposed" ]]; then
                    echo "- [$link_text]($relpath) — $e_summary _(proposed)_"
                elif [[ "$e_status" == "todo" ]]; then
                    echo "- [$link_text]($relpath) — $e_summary _(todo)_"
                else
                    echo "- [$link_text]($relpath) — $e_summary"
                fi
            done
            echo ""
        done

        echo "---"
        echo ""
        echo "## Summary"
        echo ""
        local proposed_c=0 todo_c=0 current_c=0 history_c=0
        for entry in "${ALL_ENTRIES[@]}"; do
            case "${entry%%|*}" in
                proposed) proposed_c=$((proposed_c + 1)) ;;
                todo)     todo_c=$((todo_c + 1)) ;;
                current)  current_c=$((current_c + 1)) ;;
                history)  history_c=$((history_c + 1)) ;;
            esac
        done
        echo "| State | Count |"
        echo "|-------|-------|"
        echo "| Proposed | $proposed_c |"
        echo "| Todo | $todo_c |"
        echo "| Current | $current_c |"
        echo "| History | $history_c |"
        echo "| **Total** | **$((${#ALL_ENTRIES[@]}))** |"
    } > "$INDEX_MD"
}

# --- Generate INDEX.html (interactive, JS-rendered) ---
generate_index_html() {
    # Build JSON data
    local json_entries="["

    for entry in "${ALL_ENTRIES[@]}"; do
        local e_state e_proj e_module e_slug e_status e_summary e_filepath
        IFS='|' read -r e_state e_proj e_module e_slug e_status e_summary e_filepath <<< "$entry"

        # Escape for JSON
        local esc_summary
        esc_summary="${e_summary//\"/\\\"}"
        esc_summary="${esc_summary//\\/\\\\}"

        local relpath="${e_filepath#$REQS_DIR/}"

        # Escape strings for JSON
        local esc_proj="${e_proj//\"/\\\"}"
        local esc_module="${e_module//\"/\\\"}"
        local esc_slug="${e_slug//\"/\\\"}"
        local esc_status="${e_status//\"/\\\"}"
        local esc_relpath="${relpath//\"/\\\"}"

        [[ "$json_entries" != "[" ]] && json_entries+=","
        json_entries+="{\"state\":\"$e_state\",\"project\":\"$esc_proj\",\"module\":\"$esc_module\",\"slug\":\"$esc_slug\",\"status\":\"$esc_status\",\"summary\":\"$esc_summary\",\"path\":\"$esc_relpath\"}"
    done
    json_entries+="]"

    cat > "$INDEX_HTML" <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Requirements Ledger</title>
<style>
  :root {
    --bg: #0d1117; --fg: #c9d1d9; --card: #161b22; --border: #30363d;
    --proposed: #f0883e; --todo: #58a6ff; --current: #3fb950; --history: #8b949e;
    --link: #58a6ff;
  }
  @media (prefers-color-scheme: light) {
    :root { --bg:#fff; --fg:#24292f; --card:#f6f8fa; --border:#d0d7de;
            --proposed:#d97706; --todo:#0969da; --current:#1a7f37; --history:#57606a; }
  }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: var(--bg); color: var(--fg); margin: 0; padding: 20px; }
  h1 { font-size: 1.5em; margin-bottom: 0.3em; }
  .meta { color: var(--history); font-size: 0.85em; margin-bottom: 1em; }
  .controls { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 1em; }
  .controls input { padding: 6px 10px; background: var(--card); color: var(--fg);
                    border: 1px solid var(--border); border-radius: 6px; flex: 1; min-width: 200px; }
  .controls select { padding: 6px 10px; background: var(--card); color: var(--fg);
                     border: 1px solid var(--border); border-radius: 6px; }
  .state-section { margin-bottom: 1.5em; }
  .state-header { font-size: 1.15em; font-weight: 600; margin-bottom: 0.5em;
                  padding-bottom: 0.3em; border-bottom: 1px solid var(--border); }
  .state-header .count { font-size: 0.8em; color: var(--history); font-weight: normal; }
  .proj-group { margin-left: 1em; margin-bottom: 0.5em; }
  .proj-name { font-weight: 600; color: var(--fg); margin: 0.4em 0 0.2em; }
  .module-group { margin-left: 1em; }
  .module-name { font-weight: 500; font-size: 0.9em; color: var(--history); margin: 0.3em 0 0.15em; }
  .entry { padding: 4px 0; font-size: 0.9em; }
  .entry a { color: var(--link); text-decoration: none; }
  .entry a:hover { text-decoration: underline; }
  .badge { display: inline-block; padding: 1px 6px; border-radius: 10px; font-size: 0.75em; }
  .badge-proposed { background: var(--proposed); color: #fff; }
  .badge-todo { background: var(--todo); color: #fff; }
  .badge-current { background: var(--current); color: #fff; }
  .badge-history { background: var(--history); color: #fff; }
  .badge-superseded { background: var(--history); color: #fff; }
  .summary { color: var(--history); }
  .empty { color: var(--history); font-style: italic; padding: 1em; }
</style>
</head>
<body>
<h1>Requirements Ledger</h1>
<p class="meta">Generated by index-requirements.sh. Four-state lifecycle: proposed → todo → current + history.</p>
<div class="controls">
  <input type="text" id="search" placeholder="Search requirements..." oninput="render()">
  <select id="filter-state" onchange="render()">
    <option value="">All states</option>
    <option value="proposed">Proposed</option>
    <option value="todo">Todo</option>
    <option value="current">Current</option>
    <option value="history">History</option>
  </select>
  <select id="filter-project" onchange="render()">
    <option value="">All projects</option>
  </select>
</div>
<div id="content"></div>
<script>
const DATA = $json_entries;

// Populate project filter
(function() {
  const projects = [...new Set(DATA.map(e => e.project))].sort();
  const sel = document.getElementById('filter-project');
  projects.forEach(p => {
    const opt = document.createElement('option');
    opt.value = p; opt.textContent = p;
    sel.appendChild(opt);
  });
})();

function render() {
  const search = document.getElementById('search').value.toLowerCase();
  const stateFilter = document.getElementById('filter-state').value;
  const projFilter = document.getElementById('filter-project').value;

  const filtered = DATA.filter(e => {
    if (stateFilter && e.state !== stateFilter) return false;
    if (projFilter && e.project !== projFilter) return false;
    if (search) {
      const hay = (e.slug + ' ' + e.summary + ' ' + e.project + ' ' + e.module).toLowerCase();
      if (!hay.includes(search)) return false;
    }
    return true;
  });

  const states = [
    {key:'proposed', label:'Proposed (draft plans, not ready)'},
    {key:'todo',     label:'Todo (ready to implement)'},
    {key:'current',  label:'Current (how the system works now)'},
    {key:'history',  label:'History (evolution log)'}
  ];

  let html = '';
  for (const st of states) {
    const entries = filtered.filter(e => e.state === st.key);
    if (entries.length === 0) continue;
    html += '<div class="state-section">';
    html += '<div class="state-header">' + st.label + ' <span class="count">(' + entries.length + ')</span></div>';

    // Group by project, then module
    const projects = [...new Set(entries.map(e => e.project))].sort();
    for (const proj of projects) {
      html += '<div class="proj-group"><div class="proj-name">' + proj + '</div>';
      const projEntries = entries.filter(e => e.project === proj);
      const modules = [...new Set(projEntries.map(e => e.module))].sort();
      for (const mod of modules) {
        html += '<div class="module-group"><div class="module-name">' + mod + '</div>';
        const modEntries = projEntries.filter(e => e.module === mod);
        for (const e of modEntries) {
          const badgeClass = 'badge-' + (e.status === 'superseded' ? 'superseded' : e.state);
          html += '<div class="entry">';
          html += '<a href="' + e.path + '">' + e.slug + '</a> ';
          html += '<span class="badge ' + badgeClass + '">' + e.status + '</span>';
          html += ' <span class="summary">' + e.summary + '</span>';
          html += '</div>';
        }
        html += '</div>';
      }
      html += '</div>';
    }
    html += '</div>';
  }

  if (!html) {
    html = '<div class="empty">No requirements match the current filters.</div>';
  }

  document.getElementById('content').innerHTML = html;
}
render();
</script>
</body>
</html>
HTMLEOF
}

generate_index_md
generate_index_html

# Count summary
proposed_c=0; todo_c=0; current_c=0; history_c=0
for entry in "${ALL_ENTRIES[@]}"; do
    case "${entry%%|*}" in
        proposed) proposed_c=$((proposed_c + 1)) ;;
        todo)     todo_c=$((todo_c + 1)) ;;
        current)  current_c=$((current_c + 1)) ;;
        history)  history_c=$((history_c + 1)) ;;
    esac
done

echo "Index written: $INDEX_MD"
echo "  proposed: $proposed_c, todo: $todo_c, current: $current_c, history: $history_c"
echo "HTML view:  $INDEX_HTML"
