#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""
Combine tutorial components into final output files.

This is the deterministic "combine" step of the codebase tutorial pipeline.
Takes abstractions, relationships, chapter order, and chapter content to produce
the final tutorial directory with index.md and chapter files.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path


def sanitize_filename(name: str) -> str:
    """Convert a name to a safe filename."""
    safe = re.sub(r'[^\w\s-]', '', name.lower())
    safe = re.sub(r'[-\s]+', '_', safe)
    return safe.strip('_')


def generate_mermaid_diagram(abstractions: list, relationships: list) -> str:
    """Generate a Mermaid flowchart from abstractions and relationships."""
    lines = ["flowchart TD"]

    for i, abstr in enumerate(abstractions):
        node_id = f"A{i}"
        name = abstr.get("name", f"Abstraction {i}").strip()
        sanitized = name.replace('"', "'").replace('\n', ' ')
        lines.append(f'    {node_id}["{sanitized}"]')

    for rel in relationships:
        from_idx = rel.get("from", 0)
        to_idx = rel.get("to", 0)
        label = rel.get("label", "").replace('"', "'").replace('\n', ' ')

        if len(label) > 30:
            label = label[:27] + "..."

        lines.append(f'    A{from_idx} -- "{label}" --> A{to_idx}')

    return "\n".join(lines)


def generate_index(
    project_name: str,
    summary: str,
    repo_url: str,
    abstractions: list,
    relationships: list,
    chapter_order: list,
) -> str:
    """Generate the index.md content."""
    mermaid = generate_mermaid_diagram(abstractions, relationships)

    content = f"# Tutorial: {project_name}\n\n"
    content += f"{summary}\n\n"

    if repo_url:
        content += f"**Source Repository:** [{repo_url}]({repo_url})\n\n"

    content += "```mermaid\n"
    content += mermaid + "\n"
    content += "```\n\n"

    content += "## Chapters\n\n"

    for i, abstraction_idx in enumerate(chapter_order):
        if 0 <= abstraction_idx < len(abstractions):
            name = abstractions[abstraction_idx].get("name", f"Chapter {i+1}").strip()
            safe_name = sanitize_filename(name)
            filename = f"{i+1:02d}_{safe_name}.md"
            content += f"{i+1}. [{name}]({filename})\n"

    content += "\n\n---\n\n"
    content += "Generated by [Codebase Tutorial Skill](https://github.com/anthropics/claude-cookbooks/tree/main/skills)"

    return content


def main():
    parser = argparse.ArgumentParser(
        description='Combine tutorial components into final output'
    )

    parser.add_argument(
        '--project-name', '-n',
        required=True,
        help='Project name'
    )
    parser.add_argument(
        '--abstractions', '-a',
        required=True,
        help='JSON file with abstractions list'
    )
    parser.add_argument(
        '--relationships', '-r',
        required=True,
        help='JSON file with relationships (summary and details)'
    )
    parser.add_argument(
        '--chapter-order', '-c',
        required=True,
        help='JSON file with ordered chapter indices'
    )
    parser.add_argument(
        '--chapters', '-C',
        required=True,
        help='Directory containing chapter markdown files (01.md, 02.md, ...)'
    )
    parser.add_argument(
        '--output', '-o',
        required=True,
        help='Output directory'
    )
    parser.add_argument(
        '--repo-url', '-u',
        default='',
        help='Source repository URL'
    )

    args = parser.parse_args()

    with open(args.abstractions, 'r', encoding='utf-8') as f:
        abstractions = json.load(f)

    with open(args.relationships, 'r', encoding='utf-8') as f:
        relationships_data = json.load(f)

    summary = relationships_data.get("summary", "")
    relationship_details = relationships_data.get("details", [])

    with open(args.chapter_order, 'r', encoding='utf-8') as f:
        chapter_order = json.load(f)

    chapters_dir = Path(args.chapters)
    chapter_files = sorted(chapters_dir.glob("*.md"))

    chapters_content = []
    for cf in chapter_files:
        with open(cf, 'r', encoding='utf-8') as f:
            chapters_content.append(f.read())

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    index_content = generate_index(
        args.project_name,
        summary,
        args.repo_url,
        abstractions,
        relationship_details,
        chapter_order,
    )

    index_path = output_dir / "index.md"
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(index_content)
    print(f"Wrote {index_path}")

    for i, abstraction_idx in enumerate(chapter_order):
        if i >= len(chapters_content):
            print(f"Warning: No content for chapter {i+1}", file=sys.stderr)
            continue

        if 0 <= abstraction_idx < len(abstractions):
            name = abstractions[abstraction_idx].get("name", f"Chapter {i+1}").strip()
            safe_name = sanitize_filename(name)
            filename = f"{i+1:02d}_{safe_name}.md"

            content = chapters_content[i]
            if not content.endswith("\n\n"):
                content += "\n\n"
            content += "---\n\n"
            content += "Generated by [Codebase Tutorial Skill](https://github.com/anthropics/claude-cookbooks/tree/main/skills)"

            chapter_path = output_dir / filename
            with open(chapter_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Wrote {chapter_path}")

    print(f"\nTutorial complete! Output in: {output_dir}")


if __name__ == '__main__':
    main()
