#!/usr/bin/env bash
# Update .gitignore with Nix build result symlinks and (optionally) devbox artifacts
# Usage: update-gitignore.sh [--with-devbox] [--dry-run] [--verbose]
# Use --with-devbox to also ignore .devbox/ (generated by devbox shell/run)
# Use --dry-run to preview changes
# Use --verbose for full output

set -euo pipefail

WITH_DEVBOX=false
DRY_RUN=false
VERBOSE=false

for arg in "$@"; do
  case "$arg" in
    --with-devbox) WITH_DEVBOX=true ;;
    --dry-run)     DRY_RUN=true ;;
    --verbose)     VERBOSE=true ;;
  esac
done

NIX_ENTRIES=(
  "# Nix build result symlinks"
  "/result"
  "/result-*"
)

DEVBOX_ENTRIES=(
  "# Devbox generated artifacts"
  ".devbox/"
)

# Build the full entry list
ENTRIES=("${NIX_ENTRIES[@]}")
if [ "$WITH_DEVBOX" = true ]; then
  ENTRIES+=("${DEVBOX_ENTRIES[@]}")
fi

# Determine which marker to check for existing entries
check_marker='/result'
if [ "$WITH_DEVBOX" = true ]; then
  check_marker='.devbox/'
fi

if [ "$DRY_RUN" = true ]; then
  if [ -f .gitignore ]; then
    if grep -q "$check_marker" .gitignore 2>/dev/null; then
      echo "No changes needed — entries already in .gitignore"
    else
      echo "Would append to existing .gitignore:"
      for entry in "${ENTRIES[@]}"; do
        echo "  + $entry"
      done
    fi
  else
    echo "Would create .gitignore with:"
    for entry in "${ENTRIES[@]}"; do
      echo "  + $entry"
    done
  fi
  exit 0
fi

if [ -f .gitignore ]; then
  if grep -q "$check_marker" .gitignore 2>/dev/null; then
    if [ "$VERBOSE" = true ]; then echo "Entries already in .gitignore"; fi
    echo "no changes needed"
  else
    echo "" >> .gitignore
    for entry in "${ENTRIES[@]}"; do
      echo "$entry" >> .gitignore
    done
    if [ "$VERBOSE" = true ]; then echo "Appended entries to .gitignore"; fi
    echo "updated .gitignore"
  fi
else
  for entry in "${ENTRIES[@]}"; do
    echo "$entry" >> .gitignore
  done
  if [ "$VERBOSE" = true ]; then echo "Created .gitignore with entries"; fi
  echo "created .gitignore"
fi
