#!/usr/bin/env bash
# index-requirements.sh — regenerate INDEX.md from current/ requirements
#
# Usage:
#   index-requirements.sh
#   index-requirements.sh --root <path>
#
# Scans <root>/internal-docs/reqs/current/ for requirement files, extracts
# the Statement (first paragraph after frontmatter), and writes
# <root>/internal-docs/reqs/INDEX.md.

set -euo pipefail

# Args
ROOT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root) ROOT="$2"; shift 2 ;;
        -h|--help)
            head -10 "$0" | tail -8
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$ROOT" ]]; then
    ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
fi

REQS_DIR="$ROOT/internal-docs/reqs"
CURRENT_DIR="$REQS_DIR/current"
INDEX_FILE="$REQS_DIR/INDEX.md"

if [[ ! -d "$CURRENT_DIR" ]]; then
    echo "Error: no requirements directory at $CURRENT_DIR" >&2
    exit 1
fi

# Collect requirements: project, module, slug, status, statement
# Each file is at current/{proj}/{module}/{proj}_{module}_{slug}.md
declare -a ENTRIES

while IFS= read -r filepath; do
    [[ -z "$filepath" ]] && continue

    # Extract proj/module/slug from path
    rel="${filepath#$CURRENT_DIR/}"
    proj="${rel%%/*}"
    rest="${rel#*/}"
    module="${rest%%/*}"
    filename="${rest#*/}"
    # filename is {proj}_{module}_{slug}.md — strip prefix and suffix
    slug="${filename#${proj}_${module}_}"
    slug="${slug%.md}"

    # Extract status from frontmatter
    status="$(awk '/^---$/{c++; next} c==1 && /^status:/{gsub(/^status:[[:space:]]*/,""); print; exit}' "$filepath")"
    [[ -z "$status" ]] && status="active"

    # Extract statement: first non-empty, non-heading, non-frontmatter line
    statement="$(awk '
        /^---$/{fm++; next}
        fm<2 && /^#/{next}
        fm<2 && /^[[:space:]]*$/{next}
        fm>=2 {print; exit}
    ' "$filepath")"
    # Truncate statement to 80 chars
    if [[ ${#statement} -gt 80 ]]; then
        statement="${statement:0:77}..."
    fi

    ENTRIES+=("$proj|$module|$slug|$status|$statement")
done < <(find "$CURRENT_DIR" -name '*.md' -type f | sort)

# Group by project, then module
{
    echo "# Requirements Ledger — Current State"
    echo ""
    echo "_Generated by index-requirements.sh. Do not edit manually._"
    echo ""

    current_proj=""
    current_module=""

    for entry in "${ENTRIES[@]}"; do
        IFS='|' read -r proj module slug status statement <<< "$entry"

        if [[ "$proj" != "$current_proj" ]]; then
            current_proj="$proj"
            current_module=""
            echo "## $proj"
        fi

        if [[ "$module" != "$current_module" ]]; then
            current_module="$module"
            echo ""
            echo "### $module"
        fi

        link="current/$proj/$module/${proj}_${module}_${slug}.md"
        if [[ "$status" == "superseded" ]]; then
            echo "- [$slug]($link) — $statement _(superseded)_"
        else
            echo "- [$slug]($link) — $statement"
        fi
    done
} > "$INDEX_FILE"

echo "Index written: $INDEX_FILE ($(echo "${ENTRIES[@]}" | wc -w | tr -d ' ') requirements)"
